baseURL = "https://jannikmenzel.me/"
canonifyURLs = true
languageCode = 'de'
title = 'Jannik Menzel'
disableKinds = ["taxonomy", "RSS"]
[minify]

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

disableXML = true