baseURL = "https://jannikmenzel.me/"
canonifyURLs = true
title = "Jannik Menzel"
languageCode = "de"
defaultContentLanguage = "de"
enableRobotsTXT = true

pagination.pagerSize = 10
summaryLength = 70
disableKinds = ["taxonomy", "RSS"]
[minify]

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'